### PR TITLE
Don't deconst iconv input buffer under Windows

### LINKED ISSUE #51: "cannot convert argument 2 from 'char **' to 'const char **'" under MSVC
Under MSVC, https://github.com/libofx/libofx/commit/9023c0f8b7744baebb28e2ff9b9e6e54ed0a4d33 causes MSVC to fail with:

```
 error C2664: 'size_t iconv(iconv_t,const char **,size_t *,char **,size_t *)': cannot convert argument 2 from 'char **' to 'const char **'
```

This isn't an issue under vcpkg, though, likely due to some leniency stemming from a particular set of compiler switches.

### PR DESCRIPTION
**Pull request by wrobelda**
Fixes #51

### CODE REVIEW

File: lib/ofx_preproc.cpp [hunk 1]
```diff
@@ -308,7 +308,11 @@ int ofx_proc_file(LibofxContextPtr ctx, const char * p_filename)
             const char* inchar = s_buffer.c_str();
             char * outchar = iconv_buffer;
             int iconv_retval = iconv (conversion_descriptor,
+#ifdef _WIN32 //Win32's iconv implementation takes a const char** inchar
```
Comment (cstim) [inline lib/ofx_preproc.cpp:311]: I agree with the change here in general.

BUT: If you enclose some code in an #ifdef-#else-#endif, then this clause be limited to ONLY the code that actually changes with this condition. Do NOT duplicate unchanged code into both branches of this clause (unless really really necessary, which is definitely not the case here). Don't duplicate `&inbytesleft` but rather move it to a new line.

**Review by cstim — CHANGES_REQUESTED** [review]

File: lib/ofx_preproc.cpp (hunk 1 above)
Comment (cstim) [reply lib/ofx_preproc.cpp:311]: (oh, I just saw jralls proposed this himself - so don't take this too harsh, but before getting this merged, please make this basic code cleanup anyway)

Comment (wrobelda) [reply lib/ofx_preproc.cpp:311]: Absolutely, good point. Fixed.

**Review by cstim — APPROVED** [review]
